; ----- Configuración PHP para producción -----
memory_limit = 512M
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 60
max_input_vars = 5000
date.timezone = America/La_Paz

; OPcache (acelera Laravel notablemente)
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.revalidate_freq = 0

; No exponer la versión de PHP
expose_php = Off
